### ISSUE TITLE
Alerting overhaul - looking for feedback on what needs fixing

### ISSUE THREAD

**Issue by laf** [librenms/librenms#8353]
Hi Folks,

We are currently going through doing an overhaul on various aspects of the alerting system. This includes:

- [x] The rule builder (#8293)
- [x] Update the device / group mapping for alert rules (#8293)
- [x] Update the templating system to use something more solid (#8803)
- [x] Provide the ability to map specific transports to alert rules + provide custom configuration to those transports per alert rule (i.e multiple email addresses for mail transport). (#8660)
- [x] Allow transports to be configured multiple times / multiple 'destinations' (#8660)
- [ ] Attach / embed graphs
- [x] Ability to not send recovery emails (#8430)
- [x] Record the user who acknowledged an alert + message (#8433)
- [x] Add support for grouping rules based on MySQL AVG, MIN, MAX, etc (#9094)
- [ ] Track faults individually (for example each port or bgp session)

If you like the above but have nothing to add, simply use the 👍 against this post. Do not reply with comments.

If you would like to have additional functionality / changes done during this time please reply with the answers to these questions:

1. What do you require to be added or changed?
2. Will this benefit other users?
3. Would you class this as a nice to have or a requirement for an alerting system.
4. Are you willing to be involved in helping test? If so, please do not commit to this unless you have the time to spare. We will be looking for feedback within days of writing code and cannot wait weeks for responses.

Anything comments not appropriate to this or that don't provide the correct info will be deleted.

**Comment by FTBZ** [comment]
Provide the ability to map specific transports to alert rules

**Comment by murrant** [comment]
Allow transports to be configured multiple times
Allow transports to provide a list of targets (like multiple channels for Slack)

**Comment by murrant** [comment]
**Huge project alert** Use Laravel Notifications for delivering alerts https://laravel.com/docs/5.6/notifications

**Comment by Rosiak** [comment]
Ability to manually clear active alerts from the GUI.

**Comment by Sneddo** [comment]
Permissions for alert acknowledgement. 

Currently accounts with global read user level can acknowledge alerts. It would be nice to have this as an optional configuration to allow only users with administrator access to the related device able to acknowledge alerts.

**Comment by Sneddo** [comment]
Acknowledgment message.

Similar to recording the name of the user that acknowledged an alert, being able to add a short message to the alert would be very helpful. e.g. If a device is down due to a power outage this could be noted with an expected ETA, or record an incident ticket number etc.

**Comment by laf** [comment]
> Huge project alert Use Laravel Notifications for delivering alerts laravel.com/docs/5.6/notifications

I'm not sure I fancy that right now. It would mean re-writing all the transports into Laravel.

**Comment by laf** [comment]
> Permissions for alert acknowledgement.
> 
> Currently accounts with global read user level can acknowledge alerts. It would be nice to have this as an optional configuration to allow only users with administrator access to the related device able to acknowledge alerts.

I'm not adding this right now. That's more a user / permissions thing which needs an overhaul anyway.

**Comment by network-guy** [comment]
I'd like to see the ability to disable recovery messages. I have alerts for BGP sessions getting established. I like to see this, but I don't need an alert 5 minutes later when it's "recovered". 

Also, great job on the new alert rule interface. It looks a lot better and is more intuitive.

**Comment by Lonecrowe** [comment]
Would ultimately like per device the ability to assign specific 
A) Contacts (multiple) 
B) Contact Methods (API, Groups, SMS, Email
C) Contact /Alert thresholds
D) Notification order.  

A lot to do but the more granular it is,  the more awesomeness this will be.

**Comment by laf** [comment]
@Lonecrowe 
A) is above already but per rule. Per device isn't part of this scope as it's for alerting only rather than sysContact stuff.

B) Is above already but per rule.

C +D) What specifically do you want there?

More granular isn't necessarily what we are aiming for as this means more complexity so a trade off needs to be done.

**Comment by eb0815** [comment]
Hi laf, here's a bit from a somewhat-new user that needs to replace a prtg setup, so alerting is somehow high on the prio list.

Alerting systems that can be used in production are complex, rule- and hierarchy-dependent, and their functionality and features are absolutely crucial to running a 24/7 NOC team.

So here come my first two wishes...

== Escalation of alerts ==

1. Escalation procedures (from warning --x triggers/time--> error --y triggers/time--> escalated (using a different contact list), this could escalate through multiple levels

2. I believe every organisation that wants to use LibreNMS really needs this.

3. Definitely a requirement.

4. can't guarantee


== Dependencies and hierarchies ==

1. Have alerts themselves - with filtering (devices, ports, etc.) - in the alert rules, so that groups can be built, e.g. for redundant links.

2. If you want to organize your stuff redundantly and/or need to be alerted at certain threshholds of redundant links failing, you need this.

3. Given the complexity of a potential implementation, this is somewhere between a nth and a requirement.

4. can't guarantee

===========================================

Why can I not guarantee testing?
We have not changed monitoring syetems yet, we're evaluating LibreNMS, and I believe without proper alerting functionality we will not switch, so there's no time being allocated for research in that field. I'd only be able to allot personal time.

Yours, Elmar.

**Comment by murrant** [comment]
@eb0815 we already have device dependencies.
Alert escalation could be added to the list, but I wouldn't say every organization needs this.  Several transports we support do the escalation themselves (like pagerduty).

**Comment by eb0815** [comment]
Good morning Tony,

device dependencies is not the same as alert-upon-alert dependencies; some alerts might be connected to redundant setups, some not, and that also always depends on the devices/locations assigned.

**Comment by murrant** [comment]
device dependencies supports multiple parents, so it covers redundant setups.  It doesn't have anything to do with locations, but it does require manual setup right now.  The ui hopefully makes it possible to do bulk assignments easily.

**Comment by eb0815** [comment]
Re Tony,

let's just say, this is not unproblematic in a production environment - you do need automatic grouping and automatic dependencies here.

2nd topic - what about alert escalation? (This would also be made easier by alert-upon-alert dependencies)

**Comment by aldemira** [comment]
Sorry a bit late to the issue, alerting time periods were mentioned a few times in the forum, but I'd like to add it here. Please delete this comment if it is redundant. 

**What do you require to be added or changed?**

 I'd like to have the ability to add time periods to the alert rules. In that way sysadmins won't get an alert for a printer in the middle of the night.

**Will this benefit other users?**
Totally. Not every organisation has a 1st level support or a noc. Most of the places I work with has a small team of sys/net admins who bare the load of the infrastructure and it's not fair to alert them for everything 24x7

**Would you class this as a nice to have or a requirement for an alerting system.**
In most cases this is a requirement

**Are you willing to be involved in helping test? If so, please do not commit to this unless you have the time to spare. We will be looking for feedback within days of writing code and cannot wait weeks for responses.**

Yup, I'll help testing, or if you want I can help the coding effort too.

**Comment by network-guy** [comment]
@aldemira While maybe not ideal, you can handle that currently with recurring maintenance windows.

**Comment by LozBC** [comment]
Hi,

A quick thought:

_What do you require to be added or changed?_

Linked to closed issue 5973 and closed collective issues 6807.

I currently have a user that is assigned the permission Global Read. It would appear this user has the ability to acknowledge alerts which I do not think should be possible (Or maybe should be available as an option).

_Will this benefit other users?_

I think so, to be honest it was unexpected by myself that someone assigned a role labelled "read" had the ability to effect changes on the system.

_Would you class this as a nice to have or a requirement for an alerting system._

Requirement.

_Are you willing to be involved in helping test? If so, please do not commit to this unless you have the time to spare. We will be looking for feedback within days of writing code and cannot wait weeks for responses._

Yes.

**Comment by sarlacpit** [comment]
Escalations to work on timeperiods, for example 20 minutes after the node going down, an escalation could be sent. Different configurable escalation contacts would be useful.

Hierarchy - Maybe the ability to see and alert to show multiple nodes down and report a list of them with the option of immediate escalation.

**Comment by dragans** [comment]
Pretty minor request, but I think that it would be nice to have.

**1. What do you require to be added or changed?**
Allow usage of acknowledgement notes in alerting templates.

**2. Will this benefit other users?**
Yes.

**3. Would you class this as a nice to have or a requirement for an alerting system.**
Nice to have.

**4. Are you willing to be involved in helping test?**
Can't guarantee.

**Comment by laf** [comment]
@dsgagi #8713

**Comment by fallenfuzz** [comment]
transport changes are very anticipated!
Thanks for your hard work!

**Comment by amirher** [comment]
Hi,
Can we have recovery alerts available in webui?
For example, if a device status is down and show alert, web ui will also show alert when it goes back to UP status. This is important to detect intermittent cases. 
Lastly we can set the alert lifetime on the device normal state (UP) for example 1 hour before Librenms automatically purge the alert.

**Comment by murrant** [comment]
@amirher You can use the alert log to see that.

**Comment by misterHippo** [comment]
Hi :) 

I'm new to LibreNMS, but in the short time I've been working with it, I find I need the aggregate CPU alert - as per here: [https://sindrelindstad.com/projects/librenms-part3/](https://sindrelindstad.com/projects/librenms-part3/) ... apologies if this is already included now, I couldn't find any references.

**Why this?** I seem to be getting false positives for CPU utilisation; when I believe what is happening is that one core is hitting the threshold all on it's lonesome. (Windows 2012 subject, SNMP, no traps.)

Thanks! :) You're doing a great job.

(Oh, and +1 to transports per alert)

**Comment by CraigSent** [comment]
Hi, 
Macros in the new builder, macro.now, macro.past_$m are not usable. It only gives the equal yes/no option and the macro returns a timestamp.

If you try the other way; [table] > macro.past_$m it doesn't parse the macro and puts quotes around it in the query field so it evaluates as a string, example.
alert_rules.builder
`{"condition":"OR","rules":[{"id":"syslog.timestamp","field":"syslog.timestamp","type":"datetime","input":"text","operator":"greater","value":"macro.past_5m"}],"valid":true}`

alert_rules.query
`SELECT * FROM devices,syslog WHERE (devices.device_id = ? AND devices.device_id = syslog.device_id) AND syslog.timestamp > "macro.past_5m"`

Cheers

**Comment by toddjames** [comment]
**What do you require to be added or changed?**

When host dependencies were [merged in here](https://github.com/librenms/librenms/pull/7332), there was some discussion regarding polling order:

@murrant said:
> Do we need to use device dependencies to determine poller order? I could see a situation where we poll a child (especially a distant child) and the parent hasn't been polled yet. Alerts will not behave as expected here.

@laf replied:
> It would be helpful but can we easily work that out, how many levels down do you go before saying enough. I.e child device has 4 parents, one of those parents has 4 parents and so on. Also if someone accidentally sets the last parent to have a parent which is the first child.
> 
> I had thought that maybe in alerts we do an icmp check against the parents but would that slow it down too much. What about a daemon that ran doing icmp status checks all the time? We may be able to leverage fping for this.
> 
> For now I'm not sure this matters, the alerts will be suppressed once the parent host is down. Might just be worth a warning in the doc.

Correct me if I'm wrong, but this means that there may be times when a parent is polled, is determined to be up/fine, but moments later, it dies and when the children are determined to be down, they will all be alerted upon.

This can lead to unnecessary alert spam and should probably be addressed. I cannot find an open issue for this.

Tangentially, it should probably also handle packet loss and high latency dependencies. For instance, if I have high packet loss to a remote switch, I shouldn't get alerts for high packet loss on all devices behind (children of) that switch.

**Will this benefit other users?**

This will benefit anyone using host dependencies.

**Would you class this as a nice to have or a requirement for an alerting system.**

I would classify this as a nice-to-have as the person implementing alerting. However, others on my team who consume the alerts consider this a requirement.

**Are you willing to be involved in helping test? If so, please do not commit to this unless you have the time to spare. We will be looking for feedback within days of writing code and cannot wait weeks for responses.**

I am currently evaluating a replacement monitoring system and haven't tried LibreNMS because of this issue. If this issue gets traction, I would be willing to set up a test environment to test.

**Comment by laf** [comment]
I've locked this topic now.

For those people with unresolved issues I would suggest you create a feature request now on the community forum.

Why is this locked, we've implemented a good number of requests so far and have a few more todo. Spending all my time on alerting alone doesn't make any senses so I'm going to move on to other parts of the code base and come back to this another time.
